---
services:
  devcontainer-base-images:
    container_name: devcontainer-base-images
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ..:/home/vscode/base-images:cached
    user: vscode
    tty: true
