---
services:
  devcontainer-base-images:
    container_name: devcontainer-base-images
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ..:/home/vscode/base-images:cached
    user: vscode
    tty: true
