---
name: 'build python-debian'

on:
  push:
    branches:
      - main
    paths:
      - 'python/Dockerfile.debian'
  workflow_dispatch:

env:
  IMAGE: python
  DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
  DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}

permissions:
  id-token: write
  contents: read

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: 'setup qemu'
        uses: docker/setup-qemu-action@v3

      - name: 'setup docker buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'login to dockerhub'
        uses: docker/login-action@v3
        with:
          username: ${{env.DOCKERHUB_USERNAME}}
          password: ${{env.DOCKERHUB_PASSWORD}}

      - name: 'extract version from dockerfile'
        id: extract_version
        run: |
          TAG=$(sed -n 's/^FROM .*:\([^ -]*\).*/\1/p' ./${{env.IMAGE}}/Dockerfile.debian)
          echo "TAG=${TAG#v}" >> $GITHUB_ENV
          echo "TAG=${TAG#v}"
          BASE=$(sed -n 's/^FROM .*:\([^ -]*\)-\([^ -]*\).*/\2/p' ./${{env.IMAGE}}/Dockerfile.debian)
          echo "TAG=${BASE}" >> $GITHUB_ENV
          echo "TAG=${BASE}"

      - name: 'push'
        uses: docker/bake-action@v5
        with:
          targets: push-debian
          workdir: ./${{env.IMAGE}}
